package com.dhanantry.scapeandrunparasites.init;

import com.dhanantry.scapeandrunparasites.SRPMain;
import com.dhanantry.scapeandrunparasites.item.CompassColony;
import com.dhanantry.scapeandrunparasites.item.CompassNode;
import com.dhanantry.scapeandrunparasites.item.CompassOrigin;
import com.dhanantry.scapeandrunparasites.item.ItemAdvancementIcon;
import com.dhanantry.scapeandrunparasites.item.ItemAlveolarFluid;
import com.dhanantry.scapeandrunparasites.item.ItemAlveoli;
import com.dhanantry.scapeandrunparasites.item.ItemBase;
import com.dhanantry.scapeandrunparasites.item.ItemBaseNoTooltip;
import com.dhanantry.scapeandrunparasites.item.ItemBeholderPearl;
import com.dhanantry.scapeandrunparasites.item.ItemBookOfVengeance;
import com.dhanantry.scapeandrunparasites.item.ItemBough;
import com.dhanantry.scapeandrunparasites.item.ItemClockDevelopment;
import com.dhanantry.scapeandrunparasites.item.ItemClockEvolution;
import com.dhanantry.scapeandrunparasites.item.ItemDeadBlood;
import com.dhanantry.scapeandrunparasites.item.ItemDiscRecord;
import com.dhanantry.scapeandrunparasites.item.ItemDislodgementReport;
import com.dhanantry.scapeandrunparasites.item.ItemFalseApple;
import com.dhanantry.scapeandrunparasites.item.ItemFishlin;
import com.dhanantry.scapeandrunparasites.item.ItemGreekFire;
import com.dhanantry.scapeandrunparasites.item.ItemInfestedBonemeal;
import com.dhanantry.scapeandrunparasites.item.ItemLure;
import com.dhanantry.scapeandrunparasites.item.ItemMobSpawner;
import com.dhanantry.scapeandrunparasites.item.ItemModule;
import com.dhanantry.scapeandrunparasites.item.ItemPhaseReport;
import com.dhanantry.scapeandrunparasites.item.ItemSRPFieldGuide;
import com.dhanantry.scapeandrunparasites.item.ItemShrimp;
import com.dhanantry.scapeandrunparasites.item.ItemTheSignCharm;
import com.dhanantry.scapeandrunparasites.item.ItemThornshadeBerry;
import com.dhanantry.scapeandrunparasites.item.ItemThornshadeDecanter;
import com.dhanantry.scapeandrunparasites.item.ItemThrowable;
import com.dhanantry.scapeandrunparasites.item.ItemVectorMapReport;
import com.dhanantry.scapeandrunparasites.item.ItemVenkrolBoots;
import com.dhanantry.scapeandrunparasites.item.SRPArmorSetBase;
import com.dhanantry.scapeandrunparasites.item.hijacked.ItemHijackedIronAxe;
import com.dhanantry.scapeandrunparasites.item.hijacked.ItemHijackedIronHoe;
import com.dhanantry.scapeandrunparasites.item.hijacked.ItemHijackedIronPickaxe;
import com.dhanantry.scapeandrunparasites.item.hijacked.ItemHijackedIronShovel;
import com.dhanantry.scapeandrunparasites.item.hijacked.ItemHijackedIronSword;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponMeleeAxe;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponMeleeCleaver;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponMeleeLance;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponMeleeMaul;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponMeleeScythe;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponMeleeSword;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponToolArmorBase;
import com.dhanantry.scapeandrunparasites.item.tool.WeaponToolRangeBase;
import com.dhanantry.scapeandrunparasites.util.config.SRPConfig;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.event.RegistryEvent.Register;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.registries.IForgeRegistry;

public class SRPItems {
   public static List<Item> SRP_ITEMS = new ArrayList<>();
   public static Item acanra_drop;
   public static Item aemana_drop;
   public static Item ahull_drop;
   public static Item anogla_drop;
   public static Item ashyco_drop;
   public static Item abano_drop;
   public static Item aranrac_drop;
   public static Item alum_drop;
   public static Item infected_drop;
   public static Item venkrol_drop;
   public static Item dod_drop;
   public static Item pearl;
   public static Item VENKROL_BOOTS;
   public static Item itembase;
   public static Item itemAssimilate;
   public static Item itemEvolve;
   public static Item itemDevolve;
   public static Item itemVariant;
   public static Item itemthrow;
   public static Item itemEVClock;
   public static Item itemLevelClock;
   public static Item biomeCompass;
   public static Item colonyCompass;
   public static Item originCompass;
   public static Item DISLODGEMENT_REPORT;
   public static Item shrimp;
   public static Item tendrons;
   public static Item hardbone;
   public static Item infblade;
   public static Item livingcore;
   public static Item vileshell;
   public static Item bone;
   public static Item tissuespike;
   public static Item modulebase;
   public static Item organsynth;
   public static Item itemlurecomponent1;
   public static Item itemlurecomponent2;
   public static Item itemlurecomponent3;
   public static Item itemlurecomponent4;
   public static Item itemlurecomponent5;
   public static Item itemlurecomponent6;
   public static Item itemlurecomponent7;
   public static Item itemlurecomponent8;
   public static Item itemlurecomponent9;
   public static Item itemlurecomponent10;
   public static Item ALVEOLAR_FLUID;
   public static Item DEADBLOOD_FLUID;
   public static Item semiorganicingot;
   public static Item falseapple;
   public static Item fishlin;
   public static Item alveoligrowth;
   public static Item infestedbonemeal;
   public static Item signstatus;
   public static Item itemThornshadeBerry;
   public static Item bookofvengeance;
   public static Item itemmobspawner_rathol;
   public static Item itemmobspawner_gothol;
   public static Item itemmobspawner_buthol;
   public static Item itemmobspawner_lodo;
   public static Item itemmobspawner_mudo;
   public static Item itemmobspawner_nuuh;
   public static Item itemmobspawner_ata;
   public static Item itemmobspawner_venkrol;
   public static Item itemmobspawner_venkrolsii;
   public static Item itemmobspawner_venkrolsiii;
   public static Item itemmobspawner_venkrolsiv;
   public static Item itemmobspawner_tonro;
   public static Item itemmobspawner_unvo;
   public static Item itemmobspawner_nak;
   public static Item itemmobspawner_dod;
   public static Item itemmobspawner_dodsii;
   public static Item itemmobspawner_dodsiii;
   public static Item itemmobspawner_dodsiv;
   public static Item itemmobspawner_infbear;
   public static Item itemmobspawner_infhuman;
   public static Item itemmobspawner_infhumanhead;
   public static Item itemmobspawner_infenderman;
   public static Item itemmobspawner_infendermanhead;
   public static Item itemmobspawner_infcow;
   public static Item itemmobspawner_infcowhead;
   public static Item itemmobspawner_infsheep;
   public static Item itemmobspawner_infsheephead;
   public static Item itemmobspawner_infwolf;
   public static Item itemmobspawner_infwolfhead;
   public static Item itemmobspawner_dorpa;
   public static Item itemmobspawner_infsquid;
   public static Item itemmobspawner_infpig;
   public static Item itemmobspawner_infpighead;
   public static Item itemmobspawner_infvillager;
   public static Item itemmobspawner_infvillagerhead;
   public static Item itemmobspawner_inhooS;
   public static Item itemmobspawner_inhooM;
   public static Item itemmobspawner_quac;
   public static Item itemmobspawner_leer;
   public static Item itemmobspawner_infhorse;
   public static Item itemmobspawner_infhorsehead;
   public static Item itemmobspawner_infplayer;
   public static Item itemmobspawner_infplayerhead;
   public static Item itemmobspawner_infdragone;
   public static Item itemmobspawner_infdragonehead;
   public static Item itemmobspawner_ferbear;
   public static Item itemmobspawner_ferhuman;
   public static Item itemmobspawner_ferenderman;
   public static Item itemmobspawner_fercow;
   public static Item itemmobspawner_fersheep;
   public static Item itemmobspawner_ferwolf;
   public static Item itemmobspawner_ferpig;
   public static Item itemmobspawner_fervillager;
   public static Item itemmobspawner_ferhorse;
   public static Item itemmobspawner_hiblaze;
   public static Item itemmobspawner_higolem;
   public static Item itemmobspawner_hiskeleton;
   public static Item itemmobspawner_host;
   public static Item itemmobspawner_hostii;
   public static Item itemmobspawner_specow;
   public static Item itemmobspawner_spevillager;
   public static Item itemmobspawner_speenderman;
   public static Item itemmobspawner_spehuman;
   public static Item itemmobspawner_spebear;
   public static Item itemmobspawner_spesheep;
   public static Item itemmobspawner_abofaces;
   public static Item itemmobspawner_abohead;
   public static Item itemmobspawner_heed;
   public static Item itemmobspawner_cruxa;
   public static Item itemmobspawner_mes;
   public static Item itemmobspawner_lesh;
   public static Item itemmobspawner_shyco;
   public static Item itemmobspawner_hull;
   public static Item itemmobspawner_canra;
   public static Item itemmobspawner_nogla;
   public static Item itemmobspawner_emana;
   public static Item itemmobspawner_bano;
   public static Item itemmobspawner_wymo;
   public static Item itemmobspawner_iki;
   public static Item itemmobspawner_ranrac;
   public static Item itemmobspawner_lum;
   public static Item itemmobspawner_shycoadapted;
   public static Item itemmobspawner_ikiadapted;
   public static Item itemmobspawner_canraadapted;
   public static Item itemmobspawner_noglaadapted;
   public static Item itemmobspawner_hulladapted;
   public static Item itemmobspawner_emanaadapted;
   public static Item itemmobspawner_banoadapted;
   public static Item itemmobspawner_ranracadapted;
   public static Item itemmobspawner_oronco;
   public static Item itemmobspawner_terla;
   public static Item itemmobspawner_pod;
   public static Item itemmobspawner_alafha;
   public static Item itemmobspawner_anged;
   public static Item itemmobspawner_ganro;
   public static Item itemmobspawner_omboo;
   public static Item itemmobspawner_esor;
   public static Item itemmobspawner_orch;
   public static Item itemmobspawner_flog;
   public static Item itemmobspawner_jinjo;
   public static Item itemmobspawner_elvia;
   public static Item itemmobspawner_pheon;
   public static Item itemmobspawner_lencia;
   public static Item itemmobspawner_vesta;
   public static Item itemmobspawner_leem;
   public static Item itemmobspawner_leemsii;
   public static Item itemmobspawner_leemsiii;
   public static Item itemmobspawner_leemsiv;
   public static Item itemmobspawner_gim;
   public static Item itemmobspawner_gimadapted;
   public static Item itemmobspawner_zaa;
   public static Item itemmobspawner_zaaadapted;
   public static Item itemmobspawner_done;
   public static Item itemmobspawner_kirin;
   public static Item itemmobspawner_wymoadapted;
   public static Item itemmobspawner_cruxb;
   public static Item itemmobspawner_lumadapted;
   public static Item itemmobspawner_heblu;
   public static Item BLOODY_BONE;
   public static Item BLOODY_ROD;
   public static Item BLOODY_IRON_INGOT;
   public static Item ada_vermin_drop;
   public static Item ada_viscera_drop;
   public static Item hijacked_drop;
   public static Item hive_scrap;
   public static Item weapon_scythe;
   public static Item weapon_scytheSentient;
   public static Item weapon_axe;
   public static Item weapon_axeSentient;
   public static Item weapon_sword;
   public static Item weapon_swordSentient;
   public static Item weapon_cleaver;
   public static Item weapon_cleaverSentient;
   public static Item weapon_bow;
   public static Item weapon_bow_sentient;
   public static Item weapon_maul;
   public static Item weapon_maulSentient;
   public static Item weapon_lance;
   public static Item weapon_lanceSentient;
   public static Item armor_helmet;
   public static Item armor_chest;
   public static Item armor_pants;
   public static Item armor_boots;
   public static Item SRP_FIELD_GUIDE;
   public static Item THORNSHADE_DECANTER;
   public static Item BOUGH;
   public static Item GREEK_FIRE;
   public static Item armor_helmetSentient;
   public static Item armor_chestSentient;
   public static Item armor_pantsSentient;
   public static Item armor_bootsSentient;
   public static Item hijacked_iron_helmet;
   public static Item hijacked_iron_chestpiece;
   public static Item hijacked_iron_leggings;
   public static Item hijacked_iron_boots;
   public static Item GOTH_DOOR_ITEM;
   public static Item BRUSEWOOD_DOOR_ITEM;
   public static Item CONSUMED_DOOR_ITEM;
   public static Item hijacked_iron_sword;
   public static Item hijacked_iron_axe;
   public static Item hijacked_iron_shovel;
   public static Item hijacked_iron_hoe;
   public static Item hijacked_iron_pickaxe;
   public static ItemModule MOD_INBORN;
   public static ItemModule MOD_ASSIMILATED;
   public static ItemModule MOD_HIJACKED;
   public static ItemModule MOD_FERAL;
   public static ItemModule MOD_CRUDE;
   public static ItemModule MOD_PRIMITIVE;
   public static ItemModule MOD_ADAPTED;
   public static ItemModule MOD_NEXUS;
   public static ItemModule MOD_DETERRENT;
   public static ItemModule MOD_PURE;
   public static ItemModule MOD_PREEMINENT;
   public static ItemModule MOD_ANCIENT;
   public static ItemModule MOD_DESMOID;
   public static ItemModule MOD_ESCHAR;
   public static ItemModule MOD_RESISTANCE;
   public static ItemModule MOD_IDEAL;
   public static ItemModule MOD_ORIGIN;
   public static ItemModule MOD_ASSIMARA;
   public static ItemModule MOD_DERIVED;
   public static ItemModule MOD_VECTORS;
   public static ItemModule MOD_PHASE;
   public static ItemModule MOD_DISLODGEMENT;
   public static Item phase_report;
   public static Item DARK_DAYS_ICON;
   public static Item ADAPTED_ICON;
   public static Item PRIMITIVE_ICON;
   public static Item CRUDE_ICON;
   public static Item PURE_ICON;
   public static Item HUNT_SEASON_ICON;
   public static Item GUERILLA_ICON;
   public static Item ECSTASY_ICON;
   public static Item ENEMY_OF_ENEMY_ICON;
   public static Item FOG_NULLIFIER_ICON;
   public static Item SELF_DESTRUCT_ICON;
   public static Item POTION_COLUMBUS_ICON;
   public static Item POTION_STOLAS_ICON;
   public static Item HELLFIRE_CHECMICAL_WARFARE_ICON;
   public static Item COSMIC_STRUCTUREAL_FAILURE_ICON;
   public static Item ROOTS_ICON;
   public static Item disc1;
   public static Item disc2;
   public static Item disc3;
   public static Item disc4;
   public static Item disc5;
   public static Item disc6;
   public static final ToolMaterial MATERIAL_LIVING = EnumHelper.addToolMaterial("material_livings", 0, SRPConfig.weapon_living_durability, 1.0F, 1.0F, 1);
   public static final Item VECTOR_MAP = new ItemVectorMapReport("vector_map");
   public static final ArmorMaterial ARMOR_LIVING = EnumHelper.addArmorMaterial(
      "armor_livings",
      "srparasites:livings",
      SRPConfig.livingDura,
      new int[]{SRPConfig.livingBoots, SRPConfig.livingLegs, SRPConfig.livingChest, SRPConfig.livingHelm},
      1,
      SoundEvents.field_187716_o,
      SRPConfig.livingToughness
   );
   public static final ArmorMaterial ARMOR_SENTIENT = EnumHelper.addArmorMaterial(
      "armor_sentients",
      "srparasites:sentients",
      SRPConfig.sentienDura,
      new int[]{SRPConfig.sentientBoots, SRPConfig.sentientLegs, SRPConfig.sentientChest, SRPConfig.sentientHelm},
      1,
      SoundEvents.field_187716_o,
      SRPConfig.sentientToughness
   );

   private static ItemModule makeModule(String name, ItemModule.Kind kind) {
      ItemModule m = new ItemModule(name, kind);
      m.func_77637_a(SRPMain.SRP_CREATIVETAB);
      return m;
   }

   public static void init() {
      MOD_INBORN = makeModule("module_inborn", ItemModule.Kind.INBORN);
      MOD_ASSIMILATED = makeModule("module_assimilated", ItemModule.Kind.ASSIMILATED);
      MOD_HIJACKED = makeModule("module_hijacked", ItemModule.Kind.HIJACKED);
      MOD_FERAL = makeModule("module_feral", ItemModule.Kind.FERAL);
      MOD_CRUDE = makeModule("module_crude", ItemModule.Kind.CRUDE);
      MOD_PRIMITIVE = makeModule("module_primitive", ItemModule.Kind.PRIMITIVE);
      MOD_ADAPTED = makeModule("module_adapted", ItemModule.Kind.ADAPTED);
      MOD_NEXUS = makeModule("module_nexus", ItemModule.Kind.NEXUS);
      MOD_DETERRENT = makeModule("module_deterrent", ItemModule.Kind.DETERRENT);
      MOD_PURE = makeModule("module_pure", ItemModule.Kind.PURE);
      MOD_PREEMINENT = makeModule("module_preeminent", ItemModule.Kind.PREEMINENT);
      MOD_ANCIENT = makeModule("module_ancient", ItemModule.Kind.ANCIENT);
      MOD_DESMOID = makeModule("module_desmoid", ItemModule.Kind.DESMOID);
      MOD_ESCHAR = makeModule("module_eschar", ItemModule.Kind.ESCHAR);
      MOD_RESISTANCE = makeModule("module_resistance", ItemModule.Kind.RESISTANCE);
      MOD_IDEAL = makeModule("module_ideal", ItemModule.Kind.IDEAL);
      MOD_DISLODGEMENT = makeModule("module_dislodgement", ItemModule.Kind.DISLODGEMENT);
      MOD_ORIGIN = makeModule("module_origin", ItemModule.Kind.ORIGIN);
      MOD_ASSIMARA = makeModule("module_assimara", ItemModule.Kind.ASSIMARA);
      MOD_DERIVED = makeModule("module_derived", ItemModule.Kind.DERIVED);
      MOD_VECTORS = makeModule("module_vectors", ItemModule.Kind.VECTORS);
      MOD_PHASE = makeModule("module_phase", ItemModule.Kind.PHASE);
      phase_report = new ItemPhaseReport("phase_report", 1, (byte)-1);
      DARK_DAYS_ICON = new ItemAdvancementIcon("dark_days_icon");
      ADAPTED_ICON = new ItemAdvancementIcon("adapted_icon");
      PRIMITIVE_ICON = new ItemAdvancementIcon("primitive_icon");
      CRUDE_ICON = new ItemAdvancementIcon("crude_icon");
      PURE_ICON = new ItemAdvancementIcon("pure_icon");
      HUNT_SEASON_ICON = new ItemAdvancementIcon("hunt_season_icon");
      GUERILLA_ICON = new ItemAdvancementIcon("guerilla_icon");
      ECSTASY_ICON = new ItemAdvancementIcon("ecstasy_icon");
      ENEMY_OF_ENEMY_ICON = new ItemAdvancementIcon("enemy_of_enemy_icon");
      FOG_NULLIFIER_ICON = new ItemAdvancementIcon("fog_nullifier_icon");
      SELF_DESTRUCT_ICON = new ItemAdvancementIcon("self_destruct_icon");
      POTION_COLUMBUS_ICON = new ItemAdvancementIcon("potion_columbus_icon");
      POTION_STOLAS_ICON = new ItemAdvancementIcon("potion_stolas_icon");
      HELLFIRE_CHECMICAL_WARFARE_ICON = new ItemAdvancementIcon("hellfire_chemical_warfare_icon");
      COSMIC_STRUCTUREAL_FAILURE_ICON = new ItemAdvancementIcon("cosmic_structural_failure_icon");
      ROOTS_ICON = new ItemAdvancementIcon("roots_icon");
      ALVEOLAR_FLUID = new ItemAlveolarFluid("alveolar_fluid");
      DEADBLOOD_FLUID = new ItemDeadBlood("deadblood_fluid");
      SRP_FIELD_GUIDE = new ItemSRPFieldGuide();
      SRP_ITEMS.add(SRP_FIELD_GUIDE);
      THORNSHADE_DECANTER = new ItemThornshadeDecanter();
      acanra_drop = new ItemBase("ada_summoner_drop", 16, (byte)1);
      aemana_drop = new ItemBase("ada_yelloweye_drop", 16, (byte)2);
      ahull_drop = new ItemBase("ada_manducater_drop", 16, (byte)3);
      anogla_drop = new ItemBase("ada_reeker_drop", 16, (byte)4);
      ashyco_drop = new ItemBase("ada_longarms_drop", 16, (byte)5);
      abano_drop = new ItemBase("ada_bolster_drop", 16, (byte)20);
      aranrac_drop = new ItemBase("ada_arachnida_drop", 16, (byte)21);
      alum_drop = new ItemBase("ada_devourer_drop", 16, (byte)22);
      infected_drop = new ItemBase("assimilated_flesh", 16, (byte)6);
      venkrol_drop = new ItemBase("beckon_drop", 16, (byte)23);
      dod_drop = new ItemBase("dispatcher_drop", 16, (byte)24);
      pearl = new ItemBeholderPearl();
      VENKROL_BOOTS = new ItemVenkrolBoots("venkrol_boots");
      alveoligrowth = new ItemAlveoli("alveoligrowth");
      infestedbonemeal = new ItemInfestedBonemeal("infested_bonemeal");
      BOUGH = new ItemBough("bough", 1, (byte)34);
      GREEK_FIRE = new ItemGreekFire("greek_fire", 16, (byte)31);
      BLOODY_IRON_INGOT = new ItemBase("bloody_iron_ingot", 64, (byte)-1);
      BLOODY_ROD = new ItemBase("bloody_rod", 64, (byte)-1);
      BLOODY_BONE = new ItemBase("bloody_bone", 64, (byte)-1);
      ada_vermin_drop = new ItemBase("ada_vermin_drop", 64, (byte)-1);
      ada_viscera_drop = new ItemBase("ada_viscera_drop", 64, (byte)-1);
      hijacked_drop = new ItemBase("hijacked_drop", 64, (byte)-1);
      hive_scrap = new ItemBase("hive_scrap", 64, (byte)-1);
      itembase = new ItemBase("itemtab", 1, (byte)7);
      itemAssimilate = new ItemBase("itemassimilate", 1, (byte)28);
      itemEvolve = new ItemBase("itemevolve", 1, (byte)25);
      itemDevolve = new ItemBase("itemdevolve", 1, (byte)26);
      itemVariant = new ItemBase("itemvariant", 1, (byte)27);
      itemthrow = new ItemThrowable("itemthrow", 16);
      itemEVClock = new ItemClockEvolution("evclock", 1, (byte)18);
      itemLevelClock = new ItemClockDevelopment("levelclock", 1, (byte)-1);
      biomeCompass = new CompassNode("nodecompass");
      colonyCompass = new CompassColony("colonycompass");
      originCompass = new CompassOrigin("origincompass");
      DISLODGEMENT_REPORT = new ItemDislodgementReport("dislodgement_report", 1, (byte)-1);
      shrimp = new ItemShrimp("shrimp");
      hijacked_iron_sword = new ItemHijackedIronSword("hijacked_iron_sword", SRPToolMaterials.HIJACKED_IRON);
      hijacked_iron_axe = new ItemHijackedIronAxe("hijacked_iron_axe", SRPToolMaterials.HIJACKED_IRON);
      hijacked_iron_shovel = new ItemHijackedIronShovel("hijacked_iron_shovel", SRPToolMaterials.HIJACKED_IRON);
      hijacked_iron_hoe = new ItemHijackedIronHoe("hijacked_iron_hoe", SRPToolMaterials.HIJACKED_IRON);
      hijacked_iron_pickaxe = new ItemHijackedIronPickaxe("hijacked_iron_pickaxe", SRPToolMaterials.HIJACKED_IRON);
      modulebase = new ItemBaseNoTooltip("module_base", 1, (byte)0);
      tissuespike = new ItemBaseNoTooltip("tissue_spike", 1, (byte)0);
      organsynth = new ItemBaseNoTooltip("organ_synth", 1, (byte)0);
      tendrons = new ItemBase("dried_tendons", 1, (byte)8);
      infblade = new ItemBase("infectious_blade_fragment", 1, (byte)9);
      livingcore = new ItemBase("living_core", 1, (byte)10);
      vileshell = new ItemBase("vile_shell", 1, (byte)11);
      hardbone = new ItemBase("hardened_bone_handle", 1, (byte)12);
      bone = new ItemBase("bone", 16, (byte)13);
      falseapple = new ItemFalseApple("false_apple");
      semiorganicingot = new ItemBase("semiorganic_ingot", 64, (byte)14);
      fishlin = new ItemFishlin("fishlin");
      itemThornshadeBerry = new ItemThornshadeBerry();
      signstatus = new ItemTheSignCharm("the_sign_charm");
      bookofvengeance = new ItemBookOfVengeance();
      itemlurecomponent1 = new ItemLure("lurecomponent1", 16, (byte)1);
      itemlurecomponent2 = new ItemLure("lurecomponent2", 16, (byte)2);
      itemlurecomponent3 = new ItemLure("lurecomponent3", 16, (byte)3);
      itemlurecomponent4 = new ItemLure("lurecomponent4", 16, (byte)4);
      itemlurecomponent5 = new ItemLure("lurecomponent5", 16, (byte)5);
      itemlurecomponent6 = new ItemLure("lurecomponent6", 16, (byte)6);
      itemlurecomponent7 = new ItemLure("lurecomponent7", 16, (byte)7);
      itemlurecomponent8 = new ItemLure("lurecomponent8", 16, (byte)8);
      itemlurecomponent9 = new ItemLure("lurecomponent9", 16, (byte)9);
      itemlurecomponent10 = new ItemLure("lurecomponent10", 16, (byte)10);
      itemmobspawner_dorpa = new ItemMobSpawner("dorpa");
      itemmobspawner_infsquid = new ItemMobSpawner("infsquid");
      itemmobspawner_infbear = new ItemMobSpawner("infbear");
      itemmobspawner_infhuman = new ItemMobSpawner("infhuman");
      itemmobspawner_infhumanhead = new ItemMobSpawner("infhumanhead");
      itemmobspawner_infenderman = new ItemMobSpawner("infenderman");
      itemmobspawner_infendermanhead = new ItemMobSpawner("infendermanhead");
      itemmobspawner_infcow = new ItemMobSpawner("infcow");
      itemmobspawner_infcowhead = new ItemMobSpawner("infcowhead");
      itemmobspawner_infsheep = new ItemMobSpawner("infsheep");
      itemmobspawner_infsheephead = new ItemMobSpawner("infsheephead");
      itemmobspawner_infwolf = new ItemMobSpawner("infwolf");
      itemmobspawner_infwolfhead = new ItemMobSpawner("infwolfhead");
      itemmobspawner_infpig = new ItemMobSpawner("infpig");
      itemmobspawner_infpighead = new ItemMobSpawner("infpighead");
      itemmobspawner_infvillager = new ItemMobSpawner("infvillager");
      itemmobspawner_infvillagerhead = new ItemMobSpawner("infvillagerhead");
      itemmobspawner_inhooS = new ItemMobSpawner("inhoos");
      itemmobspawner_inhooM = new ItemMobSpawner("inhoom");
      itemmobspawner_infhorse = new ItemMobSpawner("infhorse");
      itemmobspawner_infhorsehead = new ItemMobSpawner("infhorsehead");
      itemmobspawner_infplayer = new ItemMobSpawner("infplayer");
      itemmobspawner_infplayerhead = new ItemMobSpawner("infplayerhead");
      itemmobspawner_infdragone = new ItemMobSpawner("infdragone");
      itemmobspawner_infdragonehead = new ItemMobSpawner("infdragonehead");
      itemmobspawner_quac = new ItemMobSpawner("quac");
      itemmobspawner_leer = new ItemMobSpawner("leer");
      itemmobspawner_ferbear = new ItemMobSpawner("ferbear");
      itemmobspawner_ferhuman = new ItemMobSpawner("ferhuman");
      itemmobspawner_fercow = new ItemMobSpawner("fercow");
      itemmobspawner_ferenderman = new ItemMobSpawner("ferenderman");
      itemmobspawner_ferhorse = new ItemMobSpawner("ferhorse");
      itemmobspawner_ferpig = new ItemMobSpawner("ferpig");
      itemmobspawner_fersheep = new ItemMobSpawner("fersheep");
      itemmobspawner_fervillager = new ItemMobSpawner("fervillager");
      itemmobspawner_ferwolf = new ItemMobSpawner("ferwolf");
      itemmobspawner_specow = new ItemMobSpawner("marcow");
      itemmobspawner_speenderman = new ItemMobSpawner("marenderman");
      itemmobspawner_spevillager = new ItemMobSpawner("marvillager");
      itemmobspawner_spehuman = new ItemMobSpawner("marhuman");
      itemmobspawner_spesheep = new ItemMobSpawner("marsheep");
      itemmobspawner_spebear = new ItemMobSpawner("marbear");
      itemmobspawner_higolem = new ItemMobSpawner("higolem");
      itemmobspawner_hiblaze = new ItemMobSpawner("hiblaze");
      itemmobspawner_hiskeleton = new ItemMobSpawner("hiskeleton");
      itemmobspawner_host = new ItemMobSpawner("host");
      itemmobspawner_hostii = new ItemMobSpawner("hostii");
      itemmobspawner_heed = new ItemMobSpawner("heed");
      itemmobspawner_cruxa = new ItemMobSpawner("cruxa");
      itemmobspawner_mes = new ItemMobSpawner("mes");
      itemmobspawner_lesh = new ItemMobSpawner("lesh");
      itemmobspawner_done = new ItemMobSpawner("done");
      itemmobspawner_cruxb = new ItemMobSpawner("cruxb");
      itemmobspawner_abofaces = new ItemMobSpawner("abobodies");
      itemmobspawner_abohead = new ItemMobSpawner("abohead");
      itemmobspawner_shyco = new ItemMobSpawner("shyco");
      itemmobspawner_canra = new ItemMobSpawner("canra");
      itemmobspawner_nogla = new ItemMobSpawner("nogla");
      itemmobspawner_hull = new ItemMobSpawner("hull");
      itemmobspawner_emana = new ItemMobSpawner("emana");
      itemmobspawner_bano = new ItemMobSpawner("bano");
      itemmobspawner_wymo = new ItemMobSpawner("wymo");
      itemmobspawner_iki = new ItemMobSpawner("iki");
      itemmobspawner_ranrac = new ItemMobSpawner("ranrac");
      itemmobspawner_lum = new ItemMobSpawner("lum");
      itemmobspawner_gim = new ItemMobSpawner("gim");
      itemmobspawner_zaa = new ItemMobSpawner("zaa");
      itemmobspawner_shycoadapted = new ItemMobSpawner("shycoadapted");
      itemmobspawner_canraadapted = new ItemMobSpawner("canraadapted");
      itemmobspawner_noglaadapted = new ItemMobSpawner("noglaadapted");
      itemmobspawner_hulladapted = new ItemMobSpawner("hulladapted");
      itemmobspawner_emanaadapted = new ItemMobSpawner("emanaadapted");
      itemmobspawner_banoadapted = new ItemMobSpawner("banoadapted");
      itemmobspawner_wymoadapted = new ItemMobSpawner("wymoadapted");
      itemmobspawner_ikiadapted = new ItemMobSpawner("ikiadapted");
      itemmobspawner_ranracadapted = new ItemMobSpawner("ranracadapted");
      itemmobspawner_lumadapted = new ItemMobSpawner("lumadapted");
      itemmobspawner_gimadapted = new ItemMobSpawner("gimadapted");
      itemmobspawner_zaaadapted = new ItemMobSpawner("zaaadapted");
      itemmobspawner_lodo = new ItemMobSpawner("lodo");
      itemmobspawner_mudo = new ItemMobSpawner("mudo");
      itemmobspawner_nuuh = new ItemMobSpawner("nuuh");
      itemmobspawner_ata = new ItemMobSpawner("ata");
      itemmobspawner_rathol = new ItemMobSpawner("rathol");
      itemmobspawner_gothol = new ItemMobSpawner("gothol");
      itemmobspawner_buthol = new ItemMobSpawner("buthol");
      itemmobspawner_venkrol = new ItemMobSpawner("venkrol");
      itemmobspawner_venkrolsii = new ItemMobSpawner("venkrolsii");
      itemmobspawner_venkrolsiii = new ItemMobSpawner("venkrolsiii");
      itemmobspawner_venkrolsiv = new ItemMobSpawner("venkrolsiv");
      itemmobspawner_tonro = new ItemMobSpawner("tonro");
      itemmobspawner_unvo = new ItemMobSpawner("unvo");
      itemmobspawner_nak = new ItemMobSpawner("nak");
      itemmobspawner_dod = new ItemMobSpawner("dod");
      itemmobspawner_dodsii = new ItemMobSpawner("dodsii");
      itemmobspawner_dodsiii = new ItemMobSpawner("dodsiii");
      itemmobspawner_dodsiv = new ItemMobSpawner("dodsiv");
      itemmobspawner_leem = new ItemMobSpawner("leem");
      itemmobspawner_leemsii = new ItemMobSpawner("leemsii");
      itemmobspawner_leemsiii = new ItemMobSpawner("leemsiii");
      itemmobspawner_leemsiv = new ItemMobSpawner("leemsiv");
      itemmobspawner_alafha = new ItemMobSpawner("alafha");
      itemmobspawner_ganro = new ItemMobSpawner("ganro");
      itemmobspawner_omboo = new ItemMobSpawner("omboo");
      itemmobspawner_esor = new ItemMobSpawner("esor");
      itemmobspawner_orch = new ItemMobSpawner("orch");
      itemmobspawner_flog = new ItemMobSpawner("flog");
      itemmobspawner_anged = new ItemMobSpawner("anged");
      itemmobspawner_jinjo = new ItemMobSpawner("jinjo");
      itemmobspawner_vesta = new ItemMobSpawner("vesta");
      itemmobspawner_pheon = new ItemMobSpawner("pheon");
      itemmobspawner_lencia = new ItemMobSpawner("lencia");
      itemmobspawner_elvia = new ItemMobSpawner("elvia");
      itemmobspawner_heblu = new ItemMobSpawner("heblu");
      itemmobspawner_kirin = new ItemMobSpawner("kirin");
      itemmobspawner_oronco = new ItemMobSpawner("oronco");
      itemmobspawner_terla = new ItemMobSpawner("terla");
      itemmobspawner_pod = new ItemMobSpawner("pod");
      weapon_scythe = new WeaponMeleeScythe(MATERIAL_LIVING, "scythe", -3.1, SRPConfig.weapon_scythe_range, SRPConfig.weapon_scythe_damage - 1, false, (byte)1);
      weapon_scytheSentient = new WeaponMeleeScythe(
         MATERIAL_LIVING, "scythe_sentient", -3.3, SRPConfig.weapon_scythe_S_range, SRPConfig.weapon_scythe_S_damage - 1, true, (byte)2
      );
      weapon_axe = new WeaponMeleeAxe(MATERIAL_LIVING, "axe", -3.1, SRPConfig.weapon_axe_range, SRPConfig.weapon_axe_damage - 1, false, (byte)3);
      weapon_axeSentient = new WeaponMeleeAxe(
         MATERIAL_LIVING, "axe_sentient", -3.3, SRPConfig.weapon_axe_S_range, SRPConfig.weapon_axe_S_damage - 1, true, (byte)4
      );
      weapon_sword = new WeaponMeleeSword(MATERIAL_LIVING, "sword", -3.1, SRPConfig.weapon_sword_range, SRPConfig.weapon_sword_damage - 1, false, (byte)5);
      weapon_swordSentient = new WeaponMeleeSword(
         MATERIAL_LIVING, "sword_sentient", -3.3, SRPConfig.weapon_sword_S_range, SRPConfig.weapon_sword_S_damage - 1, true, (byte)6
      );
      weapon_cleaver = new WeaponMeleeCleaver(
         MATERIAL_LIVING, "cleaver", -3.1, SRPConfig.weapon_cleaver_range, SRPConfig.weapon_cleaver_damage - 1, false, (byte)7
      );
      weapon_cleaverSentient = new WeaponMeleeCleaver(
         MATERIAL_LIVING, "cleaver_sentient", -3.3, SRPConfig.weapon_cleaver_S_range, SRPConfig.weapon_cleaver_S_damage - 1, true, (byte)8
      );
      weapon_maul = new WeaponMeleeMaul(MATERIAL_LIVING, "maul", -3.1, SRPConfig.weapon_maul_range, SRPConfig.weapon_maul_damage - 1, false, (byte)9);
      weapon_maulSentient = new WeaponMeleeMaul(
         MATERIAL_LIVING, "maul_sentient", -3.3, SRPConfig.weapon_maul_S_range, SRPConfig.weapon_maul_S_damage - 1, true, (byte)10
      );
      weapon_lance = new WeaponMeleeLance(MATERIAL_LIVING, "lance", -3.1, SRPConfig.weapon_lance_range, SRPConfig.weapon_lance_damage - 1, false, (byte)11);
      weapon_lanceSentient = new WeaponMeleeLance(
         MATERIAL_LIVING, "lance_sentient", -3.3, SRPConfig.weapon_lance_S_range, SRPConfig.weapon_lance_S_damage - 1, true, (byte)12
      );
      weapon_bow = new WeaponToolRangeBase(
         "bow", SRPConfig.weapon_living_durability, SRPConfig.weapon_bow_bonus, SRPConfig.weapon_bow_damageCap, SRPConfig.weapon_bow_damage, false, (byte)1
      );
      weapon_bow_sentient = new WeaponToolRangeBase(
         "bow_sentient",
         SRPConfig.weapon_living_durability,
         SRPConfig.weapon_bow_sentient_bonus,
         SRPConfig.weapon_bow_sentient_damageCap,
         SRPConfig.weapon_bow_sentient_damage,
         true,
         (byte)2
      );
      armor_helmet = new WeaponToolArmorBase(ARMOR_LIVING, "helm", 1, false, (byte)1, EntityEquipmentSlot.HEAD);
      armor_chest = new WeaponToolArmorBase(ARMOR_LIVING, "chest", 1, false, (byte)2, EntityEquipmentSlot.CHEST);
      armor_pants = new WeaponToolArmorBase(ARMOR_LIVING, "pants", 1, false, (byte)3, EntityEquipmentSlot.LEGS);
      armor_boots = new WeaponToolArmorBase(ARMOR_LIVING, "boots", 1, false, (byte)4, EntityEquipmentSlot.FEET);
      hijacked_iron_helmet = new SRPArmorSetBase("hijacked_iron_helmet");
      hijacked_iron_chestpiece = new SRPArmorSetBase("hijacked_iron_chestpiece");
      hijacked_iron_leggings = new SRPArmorSetBase("hijacked_iron_leggings");
      hijacked_iron_boots = new SRPArmorSetBase("hijacked_iron_boots");
      armor_helmetSentient = new WeaponToolArmorBase(ARMOR_SENTIENT, "helm_sentient", 1, true, (byte)5, EntityEquipmentSlot.HEAD);
      armor_chestSentient = new WeaponToolArmorBase(ARMOR_SENTIENT, "chest_sentient", 1, true, (byte)6, EntityEquipmentSlot.CHEST);
      armor_pantsSentient = new WeaponToolArmorBase(ARMOR_SENTIENT, "pants_sentient", 1, true, (byte)7, EntityEquipmentSlot.LEGS);
      armor_bootsSentient = new WeaponToolArmorBase(ARMOR_SENTIENT, "boots_sentient", 1, true, (byte)8, EntityEquipmentSlot.FEET);
      disc3 = new ItemDiscRecord("discthree", 1, (byte)3, SRPSounds.DISC3);
   }

   @EventBusSubscriber(modid = "srparasites")
   public static class RegistrationHandler {
      @SubscribeEvent
      public static void registerItems(Register<Item> event) {
         IForgeRegistry<Item> registry = event.getRegistry();
         SRPItems.init();
         event.getRegistry().registerAll(SRPItems.SRP_ITEMS.toArray(new Item[0]));
         registry.register(SRPItems.MOD_INBORN);
         registry.register(SRPItems.MOD_ASSIMILATED);
         registry.register(SRPItems.MOD_HIJACKED);
         registry.register(SRPItems.MOD_FERAL);
         registry.register(SRPItems.MOD_CRUDE);
         registry.register(SRPItems.MOD_PRIMITIVE);
         registry.register(SRPItems.MOD_ADAPTED);
         registry.register(SRPItems.MOD_NEXUS);
         registry.register(SRPItems.MOD_DETERRENT);
         registry.register(SRPItems.MOD_PURE);
         registry.register(SRPItems.MOD_PREEMINENT);
         registry.register(SRPItems.MOD_ANCIENT);
         registry.register(SRPItems.MOD_DESMOID);
         registry.register(SRPItems.MOD_ESCHAR);
         registry.register(SRPItems.MOD_RESISTANCE);
         registry.register(SRPItems.MOD_IDEAL);
         registry.register(SRPItems.MOD_DISLODGEMENT);
         registry.register(SRPItems.MOD_ORIGIN);
         registry.register(SRPItems.MOD_DERIVED);
         registry.register(SRPItems.MOD_ASSIMARA);
         registry.register(SRPItems.MOD_VECTORS);
         registry.register(SRPItems.MOD_PHASE);
         registry.register(SRPItems.alveoligrowth);
         registry.register(SRPItems.acanra_drop);
         registry.register(SRPItems.aemana_drop);
         registry.register(SRPItems.ahull_drop);
         registry.register(SRPItems.anogla_drop);
         registry.register(SRPItems.ashyco_drop);
         registry.register(SRPItems.abano_drop);
         registry.register(SRPItems.aranrac_drop);
         registry.register(SRPItems.alum_drop);
         registry.register(SRPItems.infected_drop);
         registry.register(SRPItems.venkrol_drop);
         registry.register(SRPItems.dod_drop);
         registry.register(SRPItems.pearl);
         registry.register(SRPItems.VENKROL_BOOTS);
         registry.register(SRPItems.fishlin);
         registry.register(SRPItems.ada_vermin_drop);
         registry.register(SRPItems.ada_viscera_drop);
         registry.register(SRPItems.hijacked_drop);
         registry.register(SRPItems.hive_scrap);
         registry.register(SRPItems.BLOODY_BONE);
         registry.register(SRPItems.BLOODY_ROD);
         registry.register(SRPItems.BLOODY_IRON_INGOT);
         registry.register(SRPItems.bookofvengeance);
         registry.register(SRPItems.phase_report);
         registry.register(SRPItems.DARK_DAYS_ICON);
         registry.register(SRPItems.ADAPTED_ICON);
         registry.register(SRPItems.PRIMITIVE_ICON);
         registry.register(SRPItems.CRUDE_ICON);
         registry.register(SRPItems.PURE_ICON);
         registry.register(SRPItems.HUNT_SEASON_ICON);
         registry.register(SRPItems.GUERILLA_ICON);
         registry.register(SRPItems.ECSTASY_ICON);
         registry.register(SRPItems.ENEMY_OF_ENEMY_ICON);
         registry.register(SRPItems.FOG_NULLIFIER_ICON);
         registry.register(SRPItems.SELF_DESTRUCT_ICON);
         registry.register(SRPItems.POTION_COLUMBUS_ICON);
         registry.register(SRPItems.POTION_STOLAS_ICON);
         registry.register(SRPItems.HELLFIRE_CHECMICAL_WARFARE_ICON);
         registry.register(SRPItems.COSMIC_STRUCTUREAL_FAILURE_ICON);
         registry.register(SRPItems.ROOTS_ICON);
         registry.register(SRPItems.BOUGH);
         registry.register(SRPItems.GREEK_FIRE);
         registry.register(SRPItems.itembase);
         registry.register(SRPItems.itemAssimilate);
         registry.register(SRPItems.itemEvolve);
         registry.register(SRPItems.itemDevolve);
         registry.register(SRPItems.itemVariant);
         registry.register(SRPItems.itemthrow);
         registry.register(SRPItems.itemEVClock);
         registry.register(SRPItems.itemLevelClock);
         registry.register(SRPItems.biomeCompass);
         registry.register(SRPItems.colonyCompass);
         registry.register(SRPItems.originCompass);
         registry.register(SRPItems.shrimp);
         registry.register(SRPItems.DISLODGEMENT_REPORT);
         registry.register(SRPItems.tendrons);
         registry.register(SRPItems.hardbone);
         registry.register(SRPItems.infblade);
         registry.register(SRPItems.tissuespike);
         registry.register(SRPItems.modulebase);
         registry.register(SRPItems.organsynth);
         registry.register(SRPItems.livingcore);
         registry.register(SRPItems.vileshell);
         registry.register(SRPItems.bone);
         registry.register(SRPItems.falseapple);
         registry.register(SRPItems.semiorganicingot);
         registry.register(SRPItems.signstatus);
         registry.register(SRPItems.itemThornshadeBerry);
         registry.register(SRPItems.infestedbonemeal);
         registry.register(SRPItems.VECTOR_MAP);
         registry.register(SRPItems.itemlurecomponent1);
         registry.register(SRPItems.itemlurecomponent2);
         registry.register(SRPItems.itemlurecomponent3);
         registry.register(SRPItems.itemlurecomponent4);
         registry.register(SRPItems.itemlurecomponent5);
         registry.register(SRPItems.itemlurecomponent6);
         registry.register(SRPItems.itemlurecomponent7);
         registry.register(SRPItems.itemlurecomponent8);
         registry.register(SRPItems.itemlurecomponent9);
         registry.register(SRPItems.itemlurecomponent10);
         registry.register(SRPItems.hijacked_iron_hoe);
         registry.register(SRPItems.hijacked_iron_axe);
         registry.register(SRPItems.hijacked_iron_shovel);
         registry.register(SRPItems.hijacked_iron_sword);
         registry.register(SRPItems.hijacked_iron_pickaxe);
         registry.register(SRPItems.weapon_scythe);
         registry.register(SRPItems.weapon_scytheSentient);
         registry.register(SRPItems.weapon_axe);
         registry.register(SRPItems.weapon_axeSentient);
         registry.register(SRPItems.weapon_sword);
         registry.register(SRPItems.weapon_swordSentient);
         registry.register(SRPItems.weapon_cleaver);
         registry.register(SRPItems.weapon_cleaverSentient);
         registry.register(SRPItems.weapon_bow);
         registry.register(SRPItems.weapon_bow_sentient);
         registry.register(SRPItems.weapon_maul);
         registry.register(SRPItems.weapon_maulSentient);
         registry.register(SRPItems.weapon_lance);
         registry.register(SRPItems.weapon_lanceSentient);
         registry.register(SRPItems.armor_helmet);
         registry.register(SRPItems.armor_chest);
         registry.register(SRPItems.armor_pants);
         registry.register(SRPItems.armor_boots);
         registry.register(SRPItems.armor_helmetSentient);
         registry.register(SRPItems.armor_chestSentient);
         registry.register(SRPItems.armor_pantsSentient);
         registry.register(SRPItems.armor_bootsSentient);
         registry.register(SRPItems.hijacked_iron_helmet);
         registry.register(SRPItems.hijacked_iron_chestpiece);
         registry.register(SRPItems.hijacked_iron_leggings);
         registry.register(SRPItems.hijacked_iron_boots);
         registry.register(SRPItems.disc3);
         registry.register(SRPItems.THORNSHADE_DECANTER);
      }
   }
}
